### ISSUE TITLE
nWBTC does not withdraw to fWBTC

### ISSUE THREAD

**Issue by cryptnotiq** [flamincome/contracts#5]
I successfully unwrapped to nWBTC and my balance is correct and displaying; however, when I click withdraw it shows my available balance as zero and if I enter any non-zero number it says exceeds available balance.

When I try to interact directly with the smart contracts via https://etherscan.io/address/0xbB44B36e588445D7DA61A1e2e426664d03D40888#writeContract , metamask throws an error in contracts alert.

What makes this even more weird is a friend of mine successfully withdrew nWBTC to fWBTC, so 5 minutes later I sent my nWBTC to him to try and it gave him the same error.

**Comment by cryptnotiq** [comment]
<img width="818" alt="Screen Shot 2020-10-03 at 19 48 59" src="https://user-images.githubusercontent.com/43958441/95011225-7caeeb80-062f-11eb-852a-1257515139e8.png">
<img width="398" alt="Screen Shot 2020-10-03 at 19 49 04" src="https://user-images.githubusercontent.com/43958441/95011226-7e78af00-062f-11eb-9a03-b33927c0112d.png">

**Comment by cryptnotiq** [comment]
hey, figured out the issue thanks to Adam. You have to use the same wallet address you initially deposited the tokens with. Copying Adam's response here which resolved it so anyone else can see it. 

When trying to withdraw nTokens from Flamincome, please make sure your nTokens are in the same wallet address as when you minted them. nTokens are collateral-backed synthetic tokens, so if you want to get back the fToken (collateral), you need to burn the minted nTokens, and they need to be in the same wallet address. One hint on this is to check whether you have the amount of nTokens shown under the "Minted" column, if not you must be using a different wallet address.

**Comment by flam-income** [comment]
> hey, figured out the issue thanks to Adam. You have to use the same wallet address you initially deposited the tokens with. Copying Adam's response here which resolved it so anyone else can see it.
> 
> When trying to withdraw nTokens from Flamincome, please make sure your nTokens are in the same wallet address as when you minted them. nTokens are collateral-backed synthetic tokens, so if you want to get back the fToken (collateral), you need to burn the minted nTokens, and they need to be in the same wallet address. One hint on this is to check whether you have the amount of nTokens shown under the "Minted" column, if not you must be using a different wallet address.

@cryptnotiq thank you a lot for the explanation, it will help other users understanding fTokens and nTokens
